version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
      - 49153:49153
      - 3007:3007
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next