export const translationType = {
    TRANSLATION_REQUEST: "TRANSLATION_REQUEST",
    TRANSLATION_SUCCESS: "TRANSLATION_SUCCESS",
    TRANSLATION_FAILURE: "TRANSLATION_FAILURE",
};
export const authType = {
    AUTH_REQUEST: "AUTH_REQUEST",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAILURE: "AUTH_FAILURE",
    AUTH_REGISTER_REQUEST: "AUTH_REGISTER_REQUEST",
    AUTH_INITIAL_REQUEST: "AUTH_INITIAL_REQUEST",
    AUTH_LOGOUT_REQUEST: "AUTH_LOGOUT_REQUEST",
};
export const globalType = {
    GLOBAL_SIDEBAR_TOGGLE: "GLOBAL_SIDEBAR_TOGGLE"
}
export const projectType = {
    ADD_PROJECT: "ADD_PROJECT",
}